services:
  tasker.api:
    image: tasker.api
    build:
      context: .
      dockerfile: src/Infrastructure/Tasker.Api/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Production
    env_file:
      - .env

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - ${N8N_PORT}:5678 # порт, на котором будет доступен n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL}
    volumes:
      - ./n8n_data:/data # монтирование директории для данных n8n